apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: repo-push-secret
parameters:
  - name: REPO_PUSH_SECRET_NAME
    description: Secret name to create (must match REPO_PUSH_SECRET_NAME in buildconfigs-template-repo.yaml)
    value: repo-push-secret
  - name: DOCKERCONFIGJSON
    description: >
      The contents of a docker config JSON with credentials for the target registry.
      Provide a SINGLE-LINE JSON string.
      Example:
      {"auths":{"quay.io":{"auth":"<base64(username:token)>","email":"unused"}}}
    value: ""
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${REPO_PUSH_SECRET_NAME}
    type: kubernetes.io/dockerconfigjson
    stringData:
      .dockerconfigjson: ${DOCKERCONFIGJSON}

